image: python:3.6

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - run_pipeline
  - deploy

before_script:
  - pip install tox

run_pipeline:
  stage: run_pipeline
  script:
    - tox -- mnist save-datasets config.yml
    - tox -- mnist train-model config.yml
  artifacts:
    expire_in: 1 day
    paths:
      - ~/.pipes/mnist/*.h5

deploy:
  stage: deploy
  script:
    - tox -- aws s3 sync ~/.pipes/mnist/ s3://pipesai/mnist/ --acl public-read --exclude "*" --include "*.h5"
  when: manual
