image: python:3.6

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install tox

run_pipeline:
  script:
    - tox -- mnist save-datasets config.yml
    - tox -- mnist train-model config.yml
    - tox -- aws s3 sync ~/.mlpipes/mnist/ s3://mlpipes/mnist/ --acl public-read --exclude "*" --include "*.h5"
  when: manual
