image: python:3.6

stages:
  - data
  - train
  - deploy

before_script:
  - pip install .[cpu]
  - pip install fire

build_dataset:
  stage: data
  script: make build-dataset
  when: on_success
  artifacts:
    paths:
      - data/

train_model:
  stage: train
  script: make train-model
  when: on_success
  artifacts:
    paths:
      - data/

save_feature_extractor:
  stage: deploy
  script: make save-feature-extractor
  when: on_success
