image: python:3.6

variables:
    PIP_CACHE_DIR: .cache/pip

cache:
  paths:
    - .cache/pip

stages:
  - test
  - pipeline
  - deploy

before_script:
  - pip install .[cpu]

test:
  stage: test
  script: make test
