image: python:3.6

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .tox

before_script:
  - pip install tox

full_pipeline:
  script:
    - tox -- mnist save-datasets config.yml
    - tox -- mnist train-model config.yml
    - tox -- aws configure aws_access_key_id $AWS_ACCESS_KEY_ID
    - tox -- aws configure aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - tox -- aws configure default.region $AWS_DEFAULT_REGION
    - tox -- aws s3 sync ~/.pipes/mnist/ s3://pipesai/mnist/ --acl public-read
