stages:
  gunzip-dataset:
    cmd: python main.py gunzip-dataset
    deps:
    - data/raw
    - mnist/dataset.py
    outs:
    - data/processed
  train-model:
    cmd: python main.py train-model
    deps:
    - data/processed
    - mnist/train.py
    params:
    - mnist/config.py:
      # Dataset
      - MnistConfig.batch_size
      # Training
      - MnistConfig.random_seed
      - MnistConfig.learning_rate
      - MnistConfig.max_epochs
    outs:
    - data/model.ckpt
  evaluate-model:
    cmd: python main.py evaluate-model
    deps:
    - data/processed
    - data/model.ckpt
    - mnist/evaluate.py
    metrics:
    - data/metrics.json:
        cache: false
  save-features:
    cmd: python main.py save-features
    deps:
    - data/model.ckpt
    - mnist/deploy.py
    outs:
    - data/features.pt
