stages:
  gunzip-datasets:
    cmd: python main.py gunzip-datasets
    deps:
    - data/raw
    - mnist/config.py
    - mnist/dataset.py
    outs:
    - data/processed
  train-model:
    cmd: python main.py train-model
    deps:
    - data/processed
    - mnist/config.py
    - mnist/dataset.py
    - mnist/train.py
    outs:
    - data/features.pt
