stages:
  download-dataset:
    cmd: python main.py download-dataset
    deps:
    - mnist/dataset.py
    outs:
    - data/raw
  gunzip-dataset:
    cmd: python main.py gunzip-dataset
    deps:
    - data/raw
    - mnist/dataset.py
    outs:
    - data/processed
  train-model:
    cmd: python main.py train-model
    deps:
    - data/processed
    - mnist/dataset.py
    - mnist/train.py
    params:
    - mnist/config.py:
      # Dataset
      - MnistConfig.batch_size
      # Training
      - MnistConfig.random_seed
      - MnistConfig.learning_rate
      - MnistConfig.max_epochs
    outs:
    - data/features.pt
