stages:
  save-datasets:
    cmd: mnist save-datasets
    outs:
    - data/MNIST/raw
  train-model:
    cmd: mnist train-model
    deps:
    - data/MNIST/raw
    - mnist
    outs:
    - data/features.pt
