name: train-model

on: [push]

jobs:
  run:
    runs-on: self-hosted
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v2
      - name: Run training job
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mnist-pipeline
        run: |
          pip install poetry
          poetry install
          mnist launch-sagemaker-train $ECR_REGISTRY/$ECR_REPOSITORY:${BRANCH_NAME}
