name: build-image

on:
  push:
    paths:
      - 'mnist/**'
      - 'Dockerfile'
      - '.github/workflows/docker.yaml'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mnist-pipeline
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          echo "WANDB_API_KEY=$WANDB_API_KEY" > .env
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME
