name: test-pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Test pipeline
        run: |
          pip install .
          dvc pull data/raw
          dvc exp run
          dvc push data/features.pt
