name: pipeline

on: push

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Train model
        run: |
          pip install poetry==1.1.6
          poetry install
          dvc pull data/raw
          dvc repro
      - name: CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$(dvc metrics diff main)" ]
          then
            echo "## Metrics" >> report.md
            git fetch --prune --unshallow
            dvc metrics diff main --show-md >> report.md
            cml send-comment report.md
          fi
      - name: Push model and commit dvc.lock
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |      
          dvc push -r s3 data/features.pt
          cml pr .
